// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: sync.proto

package arcalbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpdateType represents the type of configuration update
type UpdateType int32

const (
	UpdateType_UPDATE_TYPE_UNSPECIFIED UpdateType = 0
	UpdateType_UPDATE_TYPE_FULL        UpdateType = 1 // Full configuration snapshot
	UpdateType_UPDATE_TYPE_INCREMENTAL UpdateType = 2 // Incremental update
	UpdateType_UPDATE_TYPE_HEARTBEAT   UpdateType = 3 // Heartbeat/keepalive
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "UPDATE_TYPE_UNSPECIFIED",
		1: "UPDATE_TYPE_FULL",
		2: "UPDATE_TYPE_INCREMENTAL",
		3: "UPDATE_TYPE_HEARTBEAT",
	}
	UpdateType_value = map[string]int32{
		"UPDATE_TYPE_UNSPECIFIED": 0,
		"UPDATE_TYPE_FULL":        1,
		"UPDATE_TYPE_INCREMENTAL": 2,
		"UPDATE_TYPE_HEARTBEAT":   3,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_sync_proto_enumTypes[0].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_sync_proto_enumTypes[0]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

// GetConfigRequest requests the current configuration snapshot
type GetConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: request only if revision is newer than this
	CurrentRevision int64 `protobuf:"varint,1,opt,name=current_revision,json=currentRevision,proto3" json:"current_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *GetConfigRequest) GetCurrentRevision() int64 {
	if x != nil {
		return x.CurrentRevision
	}
	return 0
}

// GetConfigResponse returns the current configuration snapshot
type GetConfigResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Config *ConfigSnapshot        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// If current_revision in request matches, config may be empty
	Unchanged     bool `protobuf:"varint,2,opt,name=unchanged,proto3" json:"unchanged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigResponse) GetConfig() *ConfigSnapshot {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetConfigResponse) GetUnchanged() bool {
	if x != nil {
		return x.Unchanged
	}
	return false
}

// WatchConfigRequest initiates a configuration watch stream
type WatchConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent ID
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Current revision the agent has
	CurrentRevision int64 `protobuf:"varint,2,opt,name=current_revision,json=currentRevision,proto3" json:"current_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchConfigRequest) Reset() {
	*x = WatchConfigRequest{}
	mi := &file_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConfigRequest) ProtoMessage() {}

func (x *WatchConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConfigRequest.ProtoReflect.Descriptor instead.
func (*WatchConfigRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2}
}

func (x *WatchConfigRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *WatchConfigRequest) GetCurrentRevision() int64 {
	if x != nil {
		return x.CurrentRevision
	}
	return 0
}

// WatchConfigResponse streams configuration updates
type WatchConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of update
	Type UpdateType `protobuf:"varint,1,opt,name=type,proto3,enum=arcalb.v1.UpdateType" json:"type,omitempty"`
	// Updated configuration snapshot
	Config *ConfigSnapshot `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// Error message if any
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConfigResponse) Reset() {
	*x = WatchConfigResponse{}
	mi := &file_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConfigResponse) ProtoMessage() {}

func (x *WatchConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConfigResponse.ProtoReflect.Descriptor instead.
func (*WatchConfigResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{3}
}

func (x *WatchConfigResponse) GetType() UpdateType {
	if x != nil {
		return x.Type
	}
	return UpdateType_UPDATE_TYPE_UNSPECIFIED
}

func (x *WatchConfigResponse) GetConfig() *ConfigSnapshot {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *WatchConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RegisterAgentRequest registers an agent
type RegisterAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent hostname or identifier
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Agent version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Agent metadata (e.g., IP address, region, etc.)
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterAgentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RegisterAgentResponse acknowledges agent registration
type RegisterAgentResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Initial configuration snapshot
	Config        *ConfigSnapshot `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterAgentResponse) GetConfig() *ConfigSnapshot {
	if x != nil {
		return x.Config
	}
	return nil
}

// HeartbeatRequest sends agent heartbeat
type HeartbeatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CurrentRevision int64                  `protobuf:"varint,2,opt,name=current_revision,json=currentRevision,proto3" json:"current_revision,omitempty"`
	// Agent status information
	Status        *AgentStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentRevision() int64 {
	if x != nil {
		return x.CurrentRevision
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() *AgentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// HeartbeatResponse acknowledges heartbeat
type HeartbeatResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// If configuration has changed, new_revision will be set
	NewRevision int64 `protobuf:"varint,2,opt,name=new_revision,json=newRevision,proto3" json:"new_revision,omitempty"`
	// Controller may request agent to re-sync
	ResyncRequired bool `protobuf:"varint,3,opt,name=resync_required,json=resyncRequired,proto3" json:"resync_required,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetNewRevision() int64 {
	if x != nil {
		return x.NewRevision
	}
	return 0
}

func (x *HeartbeatResponse) GetResyncRequired() bool {
	if x != nil {
		return x.ResyncRequired
	}
	return false
}

// AgentStatus represents the current status of an agent
type AgentStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of active VIPs
	ActiveVips int32 `protobuf:"varint,1,opt,name=active_vips,json=activeVips,proto3" json:"active_vips,omitempty"`
	// Number of active backends
	ActiveBackends int32 `protobuf:"varint,2,opt,name=active_backends,json=activeBackends,proto3" json:"active_backends,omitempty"`
	// VPP status
	VppConnected bool `protobuf:"varint,3,opt,name=vpp_connected,json=vppConnected,proto3" json:"vpp_connected,omitempty"`
	// FRR status
	FrrConnected bool `protobuf:"varint,4,opt,name=frr_connected,json=frrConnected,proto3" json:"frr_connected,omitempty"`
	// Error count
	ErrorCount    int32 `protobuf:"varint,5,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{8}
}

func (x *AgentStatus) GetActiveVips() int32 {
	if x != nil {
		return x.ActiveVips
	}
	return 0
}

func (x *AgentStatus) GetActiveBackends() int32 {
	if x != nil {
		return x.ActiveBackends
	}
	return 0
}

func (x *AgentStatus) GetVppConnected() bool {
	if x != nil {
		return x.VppConnected
	}
	return false
}

func (x *AgentStatus) GetFrrConnected() bool {
	if x != nil {
		return x.FrrConnected
	}
	return false
}

func (x *AgentStatus) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\tarcalb.v1\x1a\fconfig.proto\"=\n" +
	"\x10GetConfigRequest\x12)\n" +
	"\x10current_revision\x18\x01 \x01(\x03R\x0fcurrentRevision\"d\n" +
	"\x11GetConfigResponse\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.arcalb.v1.ConfigSnapshotR\x06config\x12\x1c\n" +
	"\tunchanged\x18\x02 \x01(\bR\tunchanged\"Z\n" +
	"\x12WatchConfigRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12)\n" +
	"\x10current_revision\x18\x02 \x01(\x03R\x0fcurrentRevision\"\x89\x01\n" +
	"\x13WatchConfigResponse\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.arcalb.v1.UpdateTypeR\x04type\x121\n" +
	"\x06config\x18\x02 \x01(\v2\x19.arcalb.v1.ConfigSnapshotR\x06config\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xd3\x01\n" +
	"\x14RegisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12I\n" +
	"\bmetadata\x18\x03 \x03(\v2-.arcalb.v1.RegisterAgentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\x15RegisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x06config\x18\x03 \x01(\v2\x19.arcalb.v1.ConfigSnapshotR\x06config\"\x88\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12)\n" +
	"\x10current_revision\x18\x02 \x01(\x03R\x0fcurrentRevision\x12.\n" +
	"\x06status\x18\x03 \x01(\v2\x16.arcalb.v1.AgentStatusR\x06status\"y\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fnew_revision\x18\x02 \x01(\x03R\vnewRevision\x12'\n" +
	"\x0fresync_required\x18\x03 \x01(\bR\x0eresyncRequired\"\xc2\x01\n" +
	"\vAgentStatus\x12\x1f\n" +
	"\vactive_vips\x18\x01 \x01(\x05R\n" +
	"activeVips\x12'\n" +
	"\x0factive_backends\x18\x02 \x01(\x05R\x0eactiveBackends\x12#\n" +
	"\rvpp_connected\x18\x03 \x01(\bR\fvppConnected\x12#\n" +
	"\rfrr_connected\x18\x04 \x01(\bR\ffrrConnected\x12\x1f\n" +
	"\verror_count\x18\x05 \x01(\x05R\n" +
	"errorCount*w\n" +
	"\n" +
	"UpdateType\x12\x1b\n" +
	"\x17UPDATE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10UPDATE_TYPE_FULL\x10\x01\x12\x1b\n" +
	"\x17UPDATE_TYPE_INCREMENTAL\x10\x02\x12\x19\n" +
	"\x15UPDATE_TYPE_HEARTBEAT\x10\x032\xc0\x02\n" +
	"\n" +
	"ConfigSync\x12F\n" +
	"\tGetConfig\x12\x1b.arcalb.v1.GetConfigRequest\x1a\x1c.arcalb.v1.GetConfigResponse\x12N\n" +
	"\vWatchConfig\x12\x1d.arcalb.v1.WatchConfigRequest\x1a\x1e.arcalb.v1.WatchConfigResponse0\x01\x12R\n" +
	"\rRegisterAgent\x12\x1f.arcalb.v1.RegisterAgentRequest\x1a .arcalb.v1.RegisterAgentResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.arcalb.v1.HeartbeatRequest\x1a\x1c.arcalb.v1.HeartbeatResponseB0Z.github.com/akam1o/arca-lb/pkg/grpc/v1;arcalbv1b\x06proto3"

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData []byte
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)))
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sync_proto_goTypes = []any{
	(UpdateType)(0),               // 0: arcalb.v1.UpdateType
	(*GetConfigRequest)(nil),      // 1: arcalb.v1.GetConfigRequest
	(*GetConfigResponse)(nil),     // 2: arcalb.v1.GetConfigResponse
	(*WatchConfigRequest)(nil),    // 3: arcalb.v1.WatchConfigRequest
	(*WatchConfigResponse)(nil),   // 4: arcalb.v1.WatchConfigResponse
	(*RegisterAgentRequest)(nil),  // 5: arcalb.v1.RegisterAgentRequest
	(*RegisterAgentResponse)(nil), // 6: arcalb.v1.RegisterAgentResponse
	(*HeartbeatRequest)(nil),      // 7: arcalb.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 8: arcalb.v1.HeartbeatResponse
	(*AgentStatus)(nil),           // 9: arcalb.v1.AgentStatus
	nil,                           // 10: arcalb.v1.RegisterAgentRequest.MetadataEntry
	(*ConfigSnapshot)(nil),        // 11: arcalb.v1.ConfigSnapshot
}
var file_sync_proto_depIdxs = []int32{
	11, // 0: arcalb.v1.GetConfigResponse.config:type_name -> arcalb.v1.ConfigSnapshot
	0,  // 1: arcalb.v1.WatchConfigResponse.type:type_name -> arcalb.v1.UpdateType
	11, // 2: arcalb.v1.WatchConfigResponse.config:type_name -> arcalb.v1.ConfigSnapshot
	10, // 3: arcalb.v1.RegisterAgentRequest.metadata:type_name -> arcalb.v1.RegisterAgentRequest.MetadataEntry
	11, // 4: arcalb.v1.RegisterAgentResponse.config:type_name -> arcalb.v1.ConfigSnapshot
	9,  // 5: arcalb.v1.HeartbeatRequest.status:type_name -> arcalb.v1.AgentStatus
	1,  // 6: arcalb.v1.ConfigSync.GetConfig:input_type -> arcalb.v1.GetConfigRequest
	3,  // 7: arcalb.v1.ConfigSync.WatchConfig:input_type -> arcalb.v1.WatchConfigRequest
	5,  // 8: arcalb.v1.ConfigSync.RegisterAgent:input_type -> arcalb.v1.RegisterAgentRequest
	7,  // 9: arcalb.v1.ConfigSync.Heartbeat:input_type -> arcalb.v1.HeartbeatRequest
	2,  // 10: arcalb.v1.ConfigSync.GetConfig:output_type -> arcalb.v1.GetConfigResponse
	4,  // 11: arcalb.v1.ConfigSync.WatchConfig:output_type -> arcalb.v1.WatchConfigResponse
	6,  // 12: arcalb.v1.ConfigSync.RegisterAgent:output_type -> arcalb.v1.RegisterAgentResponse
	8,  // 13: arcalb.v1.ConfigSync.Heartbeat:output_type -> arcalb.v1.HeartbeatResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	file_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		EnumInfos:         file_sync_proto_enumTypes,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
